### ISSUE TITLE
signac view creates view folder in the current directory

### ISSUE THREAD

**Issue by phmalek** [glotzerlab/signac#305] opened 2020-03-18 18:38 UTC
### Description

`signac view` is supposed to create the symbolic link in the `project` directory, independent of the current directory. In the current version, `signac view` produces the `view` folder in the current directory, which can be a sub-directory of the project. This makes the database messy.

**Comment by bdice** [comment] 2020-03-19 03:20
@phmalek From reading the output of `signac view --help`, I think that the intended behavior is to act in the current working directory, not the project root. I understand why you would prefer to put it in the project root, but that would make the behavior somewhat inconsistent with other commands like `signac export`. You can use the command `signac view "$(signac config show project_dir)/view"` to get the behavior you're seeking. You can alias that command if you use it frequently. Please let us know if that solves your needs.

**Comment by phmalek** [comment] 2020-03-19 16:09
I am not still convinced. I cannot see the point, why `signac view` should be consistent with commands like `signac export` at the expense of having a messy database.

**Comment by vyasr** [comment] 2020-03-19 16:58
`signac view` is also consistent with essentially all standard UNIX commands (`mv`, `cp`, `chmod`, etc) that assume all paths are relative to the current directory. In particular, it should agree with `mkdir` since that's the first thing it does. For this reason, I think defaulting to creating the view relative to the project root causes on average more cognitive dissonance than it resolves. Practically, if I wanted to have multiple views (with different parameter layouts, for instance) I would argue that it's cleaner to put all the views into a subdirectory, and as a UNIX user I would expect that to work by changing into that directory and then creating all the views.

**Comment by mikemhenry** [comment] 2020-05-05 15:22
I think until we get a compelling reason to change the behavior, we will keep `signac view` working as is. While I'm closing this issue, if someone has an idea for how we can keep the current `signac view` behavior and also do what @phmalek want's, I'm open to it. That being said, see the workaround posted by @bdice  in the thread above.

**Closed by mikemhenry** 2020-05-05 15:22 UTC
Labels: wontfix
